/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("ktorca.kotlin-application-conventions")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":lib"))

    implementation(libs.kotlinx.coroutines.core)

    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)

    implementation(libs.logback.classic)
}

application {
    // Define the main class for the application.
    mainClass.set("ktorca.app.AppKt")
}
